### ISSUE TITLE
Improve exception message in bulk operations

### ISSUE THREAD

**Issue by mooncake4132** [joowani/python-arango#106]
It looks like when an error occurred in a bulk operation (i.e. `StandardCollection.insert_many`) fails, the exception it returns does not contain the message to explain why the operation failed.
```py
import arango


client = arango.ArangoClient()
db = client.db('test_db')
try:
    db.delete_collection('test')
except arango.exceptions.CollectionDeleteError:
    pass

col = db.create_collection('test')
col.add_persistent_index(['field1'], unique=True)

col.insert({'field1': '1', 'field2': '2'})
results = col.insert_many([{'field1': '1', 'field2': '3'}])
assert len(results) == 1

print('Useful information:\n{}'.format(results[0].response.raw_body['errorMessage']))
print('================================')
print('Actual output:\n{}'.format(results[0]))
print('================================')
print('Exception output:')
raise results[0]
```
Output
```
Useful information:
unique constraint violated - in index idx_1642743351743610880 of type persistent over 'field1'; conflicting key: 7355251
================================
Actual output:
[HTTP 202] Accepted
================================
Exception output:
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    raise results[0]
arango.exceptions.DocumentInsertError: [HTTP 202] Accepted
```
At first I thought it's a bug that ArangoDB is returning a 2xx. But from the docs it appears that this behavior is expected. Quoting from [Working with Documents](https://www.arangodb.com/docs/3.4/http/document-working-with-documents.html#create-document) down in the `Return codes` section:

In the array case only 201 or 202 is returned, but if an error occurred, the additional HTTP header X-Arango-Error-Codes is set, which contains a map of the error codes that occurred together with their multiplicities, as in: 1205:10,1210:17 which means that in 10 cases the error 1205 “illegal document handle” and in 17 cases the error 1210 “unique constraint violated” has happened.

**Comment by joowani** [comment]
Hi @mooncake4132,

I understand why you may think this is a problem. But consider this case:

```python
col.truncate()
results = col.insert_many([
    {"_key": "1"},
    {"_key": "1"},  # duplicate
    {"_key": "2"},
    {"_key": "2"},  # duplicate
])
```

The duplicates will result in errors. But the rest will succeed and the collection will have 2 new documents. And as you said, ArangoDB returns a 2xx. 

So did the API operation succeed here or not? I'm not sure.

I do think that this is an awkward design from ArangoDB. But it is what it is and the client must play by its rules. 

If python-arango were to raise an exception here, which error should it cover when there are many? Maybe just the first one? Then the user would lose information. How would the error message look like? It could be way too long if I tried to cover all of them. Perhaps we should put all the messages in a list and let the user iterate when a "parent" exception is caught? How would this parent exception look like (I might need to design a whole new exception specifically for bulk errors) and is this really better than the current solution? 

I don't think there is a "right" answer. There are pros and cons to each approach. But I do think this: it doesn't seem to be a good design to raise an exception and potentially halt the application code when some of the documents WERE inserted successfully. The client is making assumptions for the user and it is not clear to the user that the data could've changed. In my opinion this is the most important point, which is why I will probably leave things the way they are.

I do think that the documentation could be better, so I will improve it and stress that the burden is on the user to inspect the result to see what succeeded and what did not. 

Lastly, you can just do `results[0].error_message` instead of  `results[0].response.raw_body['errorMessage']`.

Thanks!

**Comment by mooncake4132** [comment]
Oops, sorry, I think I failed to elaborate my issue.

I think the API design is fine as is. I was just wondering if you could just include the error message in the string representation as well so it would say something like:

```
[HTTP 202] Accepted: unique constraint violated - in index idx_1642743351743610880 of type persistent over 'field1'; conflicting key: 7355251
```

instead of just

```
[HTTP 202] Accepted
```

This way, if I were to log all errors (returned from `insert_many`) I don't have to manually go through `.error_message` to get meaningful messages.

**Comment by joowani** [comment]
Hi @mooncake4132,

Oh I see what you mean. I misunderstood what you mean now. Ok I think this I can fix in the next release.

**Comment by joowani** [comment]
Hi @mooncake4132,

Python-arango version [5.1.0](https://github.com/joowani/python-arango/releases/tag/5.1.0) is now released! Try it out and feel free to reopen this ticket if you see any more issues.
