### ISSUE TITLE
Can't specify key type when creating Vertex or Edge objects

### ISSUE THREAD

**Issue by nhi-vanye** [joowani/python-arango#146]
Seems like I should be able to use UUIDs for vertex or edge collections like I can for base documents ?

**Comment by joowani** [comment]
Hi @nhi-vanye,

Could you elaborate what the problem is? Are you referring to an ArangoDB API that python-arango failed to cover? Or are you encountering some sort of an error? Thanks

**Comment by nhi-vanye** [comment]
I want to use UUIDs as the _key identifier, so I did

```
# documents = dumb object store
if db.has_collection('documents'):
    documents = db.collection('documents')
else:
    documents = db.create_collection('documents', key_generator='uuid')
```

However this fails (as does the corresponding `create_edge_collection`) - with an invalid keyword...

if graph.has_vertex_collection('subjects'):
    subjects = graph.vertex_collection('subjects')
else:
    subjects = graph.create_vertex_collection('subjects', key_generator='uuid')
```

**Comment by joowani** [comment]
Hi @nhi-vanye,

Yes that is by design. You can always create vertex collections using regular `create_collection` and do CRUD using `vertex_collection`  (I know it's a bit strange and awkward). Python-arango tries to provide a nice abstraction layer on top of ArangoDB, but in this case it's simply mirroring ArangoDB's [REST API](https://www.arangodb.com/docs/stable/http/gharial-management.html). I'm planning to improve this but I want to wait and see how ArangoDB's REST API evolves.

**Comment by joowani** [comment]
Closing as this does not seem to be an issue with python-arango. Please feel free to re-open if you have any other questions.
