### ISSUE TITLE
Need more clarifications over traverse function

### ISSUE THREAD

**Issue by afidegnum** [joowani/python-arango#25]
on arango.graph.Graph, 

can you please explain the following and give examples of the following functions:
init_func
sort_func
visitor_func
expander_func
filter_function

i m still having difficulties traversing the graphs, when i added contents to the child graphs, the whole traversal system changed.

**Comment by joowani** [comment]
Hi afidegnum,

For those arguments you must pass in **javascript functions** with pre-determined signatures that you must abide by. The functions allow you to customize the traversal behaviour. Python-arango is built right on top of ArangoDB's REST API, whose [documenation](https://docs.arangodb.com/3.0/HTTP/Traversal/index.html) will probably give you more information.

If you look at the link you will notice that the parameter names have changed slightly:

init_func --> init
sort_func --> sort
visitor_func --> visitor
expander_func --> expander
filter_func --> filter

Here are some examples from it:
```python
init_func="result.visited = 0; result.myVertices = [ ];"

visitor_func="result.visited.vertices.push(vertex._id);"

expander_func="var connections = [ ];if (vertex.name === \"Alice\") {config.datasource.getInEdges(vertex).forEach(function (e) {connections.push({ vertex: require(\"internal\").db._document(e._from), edge: e});});}if (vertex.name === \"Eve\") {config.datasource.getOutEdges(vertex).forEach(function (e) {connections.push({vertex: require(\"internal\").db._document(e._to), edge: e});});}return connections;"

filter_func="if (vertex.name === \"Bob\" ||     vertex.name === \"Charlie\") {  return \"exclude\";}return;"
```
Unfortunately the page doesn't seem to contain an example for sort_func. 

Due to the limitation of ArangoDB's REST API, there is no easy way to translate these capabilities to be more Pythonic, which is why I left the parameters as they are to take pure javascript strings.

**Comment by alexandropov** [comment]
what's the purpose of each functions? i m still finding hard to undersand, 
how do i traverse predefine graph paths in python?

**Comment by joowani** [comment]
Hi Alexandropov,

Have you checked out the documentation? It explains what each function does to some extent. 
If you still have unresolved questions you will have to direct them to ArangoDB team. Python-arango is simply a driver that pipes all the inputs to ArangoDB's REST API, and I'm afraid my knowledge on the internals is rather limited.

You may not need these functions at all, however. What are you trying to achieve exactly? could you give me an example with edges + vertices and how you want to traverse them in detail? 

Thanks,
Joohwan

**Comment by joowani** [comment]
Closing this out since I haven't heard back from you for a while now. Let me know if you have any other questions!
