### ISSUE TITLE
Add TTL-parameter to `StandardCollection.all()`? (Now raises CursorNextError)

### ISSUE THREAD

**Issue by fauskanger** [joowani/python-arango#82]
I have already created a StackOverflow quesion [here][so], but I thought I should add it here too.

I read about the TTL-issue in #63, and I think I have a related issue. I don't know if it's an issue with ArangoDB or python-arango.

The gist of the issue is that I expect to get a timeout when iterating over the collection:

    for journal in journals.all():
        create_author_edge(journal)

I get the same error if I use AQL ("FOR j IN journals RETURN j"). However, if I _set the `ttl`-parameter_ to a high value I _don't get an error_.

I lean towards believing that this is an issue with ArangoDB and not the driver, but nevertheless, I'd like to come with a feature request: add an optional parameter `ttl` to the `StandardCollection.all()`-method. 

This would enable the convenient `.all()`-method for iterations that takes a "long" time.

[so]: https://stackoverflow.com/questions/51613789/why-does-arangodb-using-python-arango-return-err-1600-error-cursor-not-found

**Comment by fauskanger** [comment]
I tried to make the change myself, and was looking into the ArangoDB [HTTP documentation][hd] after learning [that's what's being used][pa] by python-arango. I'm not conviced there is an easy way to add a `TTL`-parameter to the `StandardCollection.all()`-method.

I'm not sure how the [cursor][c] is being handled between fetching batches.

[c]: https://docs.arangodb.com/3.3/HTTP/AqlQueryCursor/
[hd]: https://docs.arangodb.com/3.3/HTTP/SimpleQuery/#return-all-documents
[pa]:  https://github.com/joowani/python-arango/blob/master/arango/collection.py#L671

**Comment by joowani** [comment]
Sorry for the late reply (out of the country at the moment). As you've pointed it out already, ArangoDB's simple query endpoint `/simple/all` (used by method `StandardCollection.all`) does not support the `ttl` parameter. I believe simple queries are just AQL statements executed with default cursor settings.

One solution is to discard this endpoint and use AQL, giving the user access to all cursor parameters. But this, in a way, defeats the purpose of the method. The reason why I added `Collection.all` in the first place was to let the users access endpoint `/simple/all` should they choose to use it over AQL for whatever reason.

So I think this issue is less of a technical one but more of a user interface/design problem. I am ok with using AQL under the hood. Let me know what you think.

**Comment by bangert** [comment]
We also ran into this problem and are now migrating to AQL queries. I am unsure about what "the right solution" would be.

It surprised me a bit, that i could not set the ttl on the `all()` call, which is why I would slightly prefer there to be this possibility - but I was also fully unaware of the relation to the underlying Arango API.

**Comment by joowani** [comment]
I've decided to just leave the API as is with no changes. Closing this ticket.
