### ISSUE TITLE
Insert Return New is not consistent with AQL return values.

### ISSUE THREAD

**Issue by TZubiri** [joowani/python-arango#88]
When running the following query in the AQL engine
`INSERT {name: "TEST, DELETE"} IN tasks RETURN NEW`
we get the following document returned:

```
[
  {
    "_key": "1296404",
    "_id": "tasks/1296404",
    "_rev": "_XsadP8C--_",
    "name": "TEST, DELETE"
  }
]
```

Which is different from the value returned by the python library, which is
`{'_rev': '_XsaNyEe--_', '_id': 'tasks/1295060', '_key': '1295060', 'new': {'estimatedTimeInHours': 0.4166666666666667, 'creation_date': 1541474865253, '_key': '1295060', '_id': 'tasks/1295060', '_rev': '_XsaNyEe--_', 'name': 'TEST,DELETE'}}`

Is there any reason this nested new object was left, why doesn't the python library just return the new object.

https://github.com/joowani/python-arango/blob/51b0060cd8267212f58dad1eda63b58d9c9d531d/tests/test_document.py#L83

If this is a design oversight, then it seems that it might break bakcwards compatibility based on the tests :(

Thank you.

**Comment by joowani** [comment]
Hi @TZubiri,

As I mentioned already in your other [github issue](https://github.com/joowani/python-arango/issues/89), the behavior you see here is not from python-arango, but ArangoDB's REST API. Python-arango usually tries to touch the JSON output from the REST API as little as possible. 

The "new" object is not returned by default (I'm sure you know this already). It is returned only when the `return_new` parameter is explicitly set to True. If `return_new` was left to False, only the insertion **metadata** is returned. For now, the metadata only contains the revision, id and key of the inserted document, but ArangoDB team can always add more things to this section in the future (things that are *not* part of the inserted document itself). 

In order versions of ArangoDB, the REST API returned *only* this metadata. The `return_new` flag and the "new" nested object was a feature added in later versions. It is up to the user to toggle this feature on. The user may not need to see the "new" object at all, so they may leave the `return_new` to False to minimize the data exchanged between DB/client and save network bandwidth.  

When the `return_new` flag was first introduced, I could've reformatted the JSON output from REST API within the library to something like `{"metadata": {}, "new": {}}`. But this would change the output format completely from previous versions. I hope you can see where I am going with this. The reason why things are the way they are now is precisely because I needed to maintain backward compatibility, not the other way around :)

**Comment by TZubiri** [comment]
> Hi @TZubiri,
> 

> The "new" object is not returned by default (I'm sure you know this already). It is returned only when the `return_new` parameter is explicitly set to True. If `return_new` was left to False, only the insertion **metadata** is returned. For now, the metadata only contains the revision, id and key of the inserted document, but ArangoDB team can always add more things to this section in the future (things that may _not_ be part of the inserted document itself).

I can think of instances where the driver might need to see this metadata. But is there an instance where the users of the driver might want to see the current metadata or the future metadata? This is why I mentioned the official arango dashboard not showing this metadata, it seems like it should be private to the driver.


 
> When the `return_new` flag was first introduced, I could've reformatted the JSON output from REST API within the library to something like `{"metadata": {}, "new": {}}`. But this would change the output format completely from previous versions. I hope you can see where I am going with this. The reason why things are the way they are now is precisely because I needed to maintain backward compatibility, not the other way around :)

I wouldn't propose that, my proposal is that the metadata not be returned in any of the cases, just the new inserted element.


> Cheers

**Comment by joowani** [comment]
Whether the metadata is useful to the users or not, I have no way of knowing completely. Abstracting for ease of use is one thing, but making decisions on behalf of the users and hiding information is something I try to avoid.

For example, the document revision ``_rev``  is something that could definitely be useful. On insertion, users can store the revision client side, and use it later to ensure that the data has not been altered by another request (which is the whole point of revisions in the first place). If python-arango did not return the metadata, users would be forced the query the database again to obtain it. 

Another example: I can't remember which API, but one of them returns the "time taken" (time it took for the DB server to process the request) in the result. What if ArangoDB team decided to include something like this in the metadata in the future? It would be "free" information that DB is giving to me, which I can see being very useful (for me at least) for monitoring and analysis etc.

I'm not sure why the behavior of the dashboard and the REST API is different. I'm sure ArangoDB team have their own reasons. But perhaps the dashboard should also return the metadata!

**Comment by TZubiri** [comment]
Thank you for the responses! I'm not too deep into databases so I had no idea about these special cases.

You can close this issue now!

Is there a devel mailing list in case I have any questions regarding the design of the library, or am I free to post them on this issue tracker?

Thank you!

**Comment by joowani** [comment]
No problem at all! Thank you for using python-arango and for your interest. These were great questions and I value all feedback.

I would prefer that you continue to post any future questions on the issue tracker in the case that they could be useful to others. Plus this library is maintained only by me so I don't have time to manage separate mailing list or discord.

Cheers.
