### ISSUE TITLE
simple queries are slower than aql?

### ISSUE THREAD

**Issue by seyhbold** [joowani/python-arango#9]
Hi,

I have an issue with the simple queries.

```python
artist = db.collection(Artist.collection).document(key)
```
takes ~550 ms while

```python
artist = list(db.execute_query("for a in prd_artist filter a._key == @val return a", bind_vars={'val': key}))[0]
```
only takes 110 ms

When I use the HTTP api of ArangoDB directly I see no difference.

Any chance to get this faster?

Thank you very much
Best Regards
Ludwig

**Comment by joowani** [comment]
Hi seyhbold,

I will take a look and give you an update.

Jay

**Comment by joowani** [comment]
Hi seyhbold,

I apologize for the (extremely) late replies.
The reason why the first query is slow is because some things are being eager loaded.

When you do:
```python
artist = db.collection(Artist.collection).document(key)
```
You are actually hitting multiple API endpoints as collection(Artist.collection) is eager loading its type information (e.g. whether it's an edge or document collection).

I am looking into ways to make everything lazy loaded (hopefully put in place next release). For now you can do:
```
collection = db.collection(Artist.collection)  # let the eager loading happen only once by assigning to a variable
collection.document(key1)
collection.document(key2)
colleciton.document(key3)
...
```

**Comment by seyhbold** [comment]
Hi Jay,

you're right. Storing the collection does the trick.
Code looks much cleaner now.

Many Thanks
Ludwig
