### ISSUE TITLE
multi-thread access ArangoDB very slow

### ISSUE THREAD

**Issue by Himan000** [joowani/python-arango#92]
Hi @joowani，is round-robin load balancing implemented? I found multi-thread access ArangoDB by python-rango very slow.

    for id in ids:
        if config.is_mutil_thread:
            all_tasks.append(executor.submit(test_select_single, id))
            counter += 1
            if counter == 1000:
                wait(all_tasks, return_when=ALL_COMPLETED)
                all_tasks = []
                counter = 0
                print("done one batch")
        else:
            test_select_single(id)

    if len(all_tasks) > 0 and config.is_mutil_thread:
        wait(all_tasks, return_when=ALL_COMPLETED)

def test_select_single(id):
    a_doc = a_collection.get(id)

**Comment by joowani** [comment]
Hi @Himan000,

Unfortunately no, load balancing is not added yet (I am not sure when). But it should be relatively simple to implement your own. You can write a wrapper which creates multiple ArangoClient instances, each client talking to a different coordinator. When you send a request via your wrapper, the wrapper can pick a client randomly (or round robin) and delegate the request and response. One thing to note: according to [this article](https://www.arangodb.com/2017/12/introducing-the-new-arangodb-java-driver-load-balancing/), AQL queries whose results cannot returned in a single response, must be sent to the same coordinator.

Also, in your code, it looks like your threads are sharing the same ArangoClient instance. The requests session (which ArangoClient uses under the hood by default) is blocking, so your performance will only get worse when you try to share it between threads. Each thread should initialize its own client session. You can also always consider multiprocessing instead of threading.

**Comment by joowani** [comment]
I think you just need to increase the number of pool size. Something like this in your custom HTTP client:

```
import requests
sess = requests.Session()
adapter = requests.adapters.HTTPAdapter(pool_connections=100, pool_maxsize=100)
sess.mount('http://', adapter)
```

**Comment by Himan000** [comment]
Hi @joowani ,
Connection pool full problem does not occur again with you code. Thanks. But there is another question, why most of the update jobs were fail?

```
def test_update_mutil():
    ids = get_all_ids()
    all_tasks = []
    counter = 0
    print("there are {} to handle".format(len(ids)))
    for id in ids:
        if config.is_mutil_thread:
            all_tasks.append(executor.submit(test_update_single, id))
            counter += 1
            if counter == 1000:
                wait(all_tasks, return_when=ALL_COMPLETED)
                all_tasks = []
                counter = 0
                print("done one batch")
        else:
            test_update_single(id)

    if len(all_tasks) > 0 and config.is_mutil_thread:
        wait(all_tasks, return_when=ALL_COMPLETED)

def test_update_single(id):
    try:
        entity_name_map = get_entities()
        a_doc = entity_name_map.get("a_collection").get(id)
        is_update = "11"
        a_doc["is_update"] = is_update
        entity_name_map.get("candidate").update(a_doc)

    except Exception as e:
        logging.exception(e)


if __name__ == '__main__':
    test_update_mutil() 
```

There are 100000 documents in a_collection, but only 10712 documents updated successfully,why? is there anything wrong? Thanks.

**Comment by joowani** [comment]
Hi @Himan000,

Try setting `return_result` to True and see what the response from the server for the failing cases are. It might be a problem with your logic (e.g. duplicate key).

**Comment by joowani** [comment]
The piece of code I gave you was just an example. Your client should look something like this:
```
class CustomHTTPClient(HTTPClient):

    def __init__(self):
        self._session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(pool_connections=1000,
                                                pool_maxsize=1000)
        self._session.mount('http://', adapter)
        self._session.mount('https://', adapter)

    def send_request(self,
                     method,
                     url,
                     params=None,
                     data=None,
                     headers=None,
                     auth=None):
        raw_resp = self._session.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            auth=auth,
        )
        return Response(
            method=raw_resp.request.method,
            url=raw_resp.url,
            headers=raw_resp.headers,
            status_code=raw_resp.status_code,
            status_text=raw_resp.reason,
            raw_body=raw_resp.text,
        )
```
(it should be ok using sessions again now that you are using streaming cursors)

**Comment by Himan000** [comment]
Hi @joowani ,
        Thanks for replying so soon every time ^-^. It works perfectly when the thread number is 1000(pool_connections=1000, pool_maxsize=1000). But There is still error when thread number is 4000(pool_connections=1000, pool_maxsize=1000, there 4 python programs running simultaneously with thread number 1000 for everyone). There is no error if there is only one pyhon program with thread number 4000.

_2019-01-14 10:44:11,579 - ERROR - [HTTP 412][ERR 1200] precondition failed
Traceback (most recent call last):
  File "D:/project/python/delink/delink_batch_parser/arangodb.py", line 374, in test_update_single
    entity_name_map.get("candidate").update(a_doc)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\collection.py", line 1733, in update
    return self._execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\executor.py", line 81, in execute
    return response_handler(response)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\collection.py", line 1725, in response_handler
    raise DocumentRevisionError(resp, request)
arango.exceptions.DocumentRevisionError: [HTTP 412][ERR 1200] precondition failed_

**Comment by joowani** [comment]
Hi @Himan000,

This is just a guess but it seems there is a race condition in your logic. You are doing a GET and then doing an UPDATE, two discrete steps that are NOT [atomic](https://stackoverflow.com/questions/15054086/what-does-atomic-mean-in-programming). If multiple threads are operating on the same document, then you could run into errors. The [document revision](https://docs.arangodb.com/3.0/Manual/Appendix/Glossary.html#document-revision) you have from the GET operation might be outdated because another thread already changed it. If this is the case, you must do one or more of the following:

1. Somehow make sure in your logic that no two threads/processes are operating on the same document
2. If multiple threads touching the same document is ok, then simply remove the "_rev" field from the document dictionary before you use it for update. 
3. Do not use multiprocessing/multithreading
4. Use raw transactions instead. See [here](https://python-driver-for-arangodb.readthedocs.io/en/master/transaction.html#restrictions) for sample code.
 
And no problem happy to help :)

**Comment by joowani** [comment]
I meant using raw javascript for transactions (please take a look at the example code again).

**Comment by Himan000** [comment]
Hi @joowani ，

There is still couple documents fail to update.

_2019-01-14 15:23:35,828 - ERROR - [HTTP 409][ERR 1200] conflict
Traceback (most recent call last):
  File "D:/project/python/batch_parser/arangodb.py", line 391, in test_update_single
    write='candidate'  # Specify the collections written.
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\database.py", line 264, in execute_transaction
    return self._execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\executor.py", line 81, in execute
    return response_handler(response)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\database.py", line 261, in response_handler
    raise TransactionExecuteError(resp, request)
arango.exceptions.TransactionExecuteError: [HTTP 409][ERR 1200] conflict_

```
def test_update_single(id):
    try:
        db.execute_transaction(
            command='''
            function () {{
                var db = require('internal').db;
                db.a_collection.update(params.a_key,params.a_doc);
                return true;
            }}
            ''',
            params={
                "a_key": id, "a_doc": {"is_update4": "00"}
            },
            read='candidate', 
            write='candidate' 
        )
    except Exception as e:
        logging.exception(e)
```

**Comment by Himan000** [comment]
Hi @joowani ,

The problem was solved by adding option `waitForSync=true` to the update fucntion.
```

def test_update_single(id):
    try:
        db.execute_transaction(
            command='''
            function () {{
                var db = require('internal').db;
                db.a_collection.update(params.a_key,params.a_doc,waitForSync=true);
                return true;
            }}
            ''',
            params={
                "a_key": id, "a_doc": {"is_update4": "00"}
            },
            read='a_collection', 
            write='a_collection' 
        )
    except Exception as e:
        logging.exception(e)
```

Thanks a lot for teaching me the code step by step and pay much attention and time. I think I can use python-arango for production project now.
Thanks ^-^.

**Comment by Himan000** [comment]
Hi @joowani ，

I think I can retry to send request if fail with err 1200. And the test result of my case is fine for this solution.

Thanks a lot for your time and patience.

**Comment by joowani** [comment]
No problem @Himan000 !
